###
# Criar um novo usuário
###

POST http://localhost:3001/api/savedate
Content-Type: application/json

{
 "nome": "John Doe",
 "email": "john.doe@example.com.uak",
 "telefone": "123456789"
}

###
# Obter todos os usuários
###

GET http://localhost:3001/api/checkdata

###
# Obter um usuário específico por ID
###

GET http://localhost:3001/anpm install axios
pi/checkdata/15

###
# Atualizar um usuário existente
###

PUT http://localhost:3001/api/updatedata/15
Content-Type: application/json

{
 "nome": "Updated Name",
 "email": "updated.email@example.com",
 "telefone": "987654321"
}

###
# Excluir um usuário por ID
###

DELETE http://localhost:3001/api/deletedata/1


### Testando a rota de busca de coordenadas por CEP
GET http://localhost:3001/api/cep/08141-300 HTTP/1.1


### Testando caixeiro viajante

POST http://localhost:3001/api/calculate-route HTTP/1.1
Content-Type: application/json

{
    "company": {
        "name": "Cleaning",
        "cep": "08141-300"
    },
    "client1": {
        "name": "Cliente longe",
         "cep": "08141-330"
        
        
    },
    "client2": {
        "name": "Cliente perto",
        "cep": "59920-000"
       
    }
}
